
using System;
using System.Collections.Generic;
using System.Linq;
using Rummy.Game;
using Rummy.Util;
using static Rummy.Util.Option;

namespace Rummy.AI;

public static class PotentialMoves
{
    public static (List<Meld> Melds, List<NearMeld> NearMelds) FindMelds(IEnumerable<Card> hand) {
        HashSet<Meld> melds = []; HashSet<NearMeld> nearMelds = [];
        foreach (var card in hand) {
            // Sets
            var sameRank = hand.Where(card.MatchesRank).ToList();
            if (sameRank.Count == 2) nearMelds.Add(new NearSet(sameRank));
            while (sameRank.Count >= 3) {
                melds.Add(new Set(sameRank.Count > 4 ? sameRank.SkipLast(sameRank.Count - 4) : sameRank));
                sameRank = [.. sameRank.Skip(Math.Min(sameRank.Count, 4))];
            }

            // Runs
            var sameSuit = hand.Where(card.MatchesSuit).ToList();
            HashSet<Card> potentialRun = [];

            foreach (var method in List.Of(RankImpl.IsAdjacentBelow, RankImpl.IsAdjacentAbove)) {
                Card? tempCard = card;
                while (tempCard is Card) {
                    potentialRun.Add(tempCard.Value);
                    var adjacent = sameSuit.Where(x => method(x.Rank, tempCard.Value.Rank));
                    tempCard = adjacent.Any() ? adjacent.First() : null;
                }
            }

            if (potentialRun.Count >= 3) melds.Add(new Run(potentialRun));
            else if (potentialRun.Count == 2) nearMelds.Add(new NearRun(potentialRun));

            if (sameSuit.Count > 1) {
                int rankDiff = sameSuit.Last().Rank - sameSuit.First().Rank + 1;
                if (rankDiff >= 3) nearMelds.Add(new NearRun(sameSuit));
            }
        }
        return ([.. melds], [.. nearMelds]);
    }

    public static Dictionary<Card, List<Meld>> FindLayOffs(IEnumerable<Card> hand, Round round) {
        Dictionary<Card, List<Meld>> potentialLayOffs = [];
        foreach (var player in round.Players) foreach (var meld in player.Melds)
                foreach (var card in hand) if (meld.CouldLayOff(card)) potentialLayOffs.GetOrCreate(card).Add(meld);
        return potentialLayOffs;
    }
    public static List<Meld> FindLayOffs(Card card, Round round) => FindLayOffs([card], round).TryGetValue(card, out var melds) ? melds : [];

    public record LayOff();

    public record RummyConfiguration(IEnumerable<Meld> Melds, IEnumerable<(Card Card, Meld Meld)> Layoffs, Card? Discard);

    // Find a valid rummy configuration if one exists, short-circuiting past evaluating alternate configurations
    public static RummyConfiguration FindRummyConfiguration(IEnumerable<Card> hand, Player player, Round round)
        => FindRummyConfigurations(hand, player, round, true).FirstOrDefault();

    public static IEnumerable<RummyConfiguration> FindRummyConfigurations(IEnumerable<Card> hand, Player player, Round round, bool shortCircuit = false) {
        if (player.Melds.Count != 0) return [];

        HashSet<RummyConfiguration> configurations = [];
        var potentialMelds = FindMelds(hand).Melds;
        var potentialLayoffs = FindLayOffs(hand, round);

        HashSet<IEnumerable<Meld>> meldConfigurations = [[]];
        foreach (var permutation in AllPermutations.Of(potentialMelds))
            meldConfigurations.Add(permutation.Where((x, i) => !permutation.Skip(i + 1).Any(y => x.Cards.Any(card => y.Cards.Contains(card)))));
        meldConfigurations = [.. meldConfigurations.Where((x, i) => !meldConfigurations.Skip(i + 1).Any(y => Enumerable.SequenceEqual(x, y)))];

        foreach (var meldConfiguration in meldConfigurations) {
            var remainingCardsAfterMelds = hand.DeepClone().ToList();
            meldConfiguration.ForEach(meld => meld.Cards.ForEach(card => remainingCardsAfterMelds.Remove(card)));

            // Find all permutations of immediate layoffs
            List<(Card Card, Meld Meld)> unwoundLayoffs = [];
            foreach (var (card, melds) in potentialLayoffs) foreach (var meld in melds) unwoundLayoffs.Add((card, meld));

            var layoffConfigurations = AllPermutations.Of(unwoundLayoffs).Select(x => x.ToList()).ToList();
            foreach (var layoffConfiguration in layoffConfigurations) {
                // Remove layoffs which use previously used cards (because this is operating on every possible order, this gives us each possible permutation)
                HashSet<Card> previouslyUsedCards = [];
                for (int i = 0; i < layoffConfiguration.Count; ++i) {
                    var thisCard = layoffConfiguration.ElementAt(i).Card;
                    if (previouslyUsedCards.Contains(thisCard)) { layoffConfiguration.RemoveAt(i); --i; }
                    previouslyUsedCards.Add(thisCard);
                }
            }
            // Remove duplicates generated by previous step
            for (int i = layoffConfigurations.Count - 1; i > 0; --i) {
                if (layoffConfigurations[0..i].Any(configuration => configuration.All(x => layoffConfigurations[i].Contains(x)))) layoffConfigurations.RemoveAt(i);
            }

            foreach (var layoffConfiguration in layoffConfigurations) {
                var remainingCardsAfterLayoffs = remainingCardsAfterMelds.DeepClone().Where(card => !layoffConfiguration.Any(x => x.Card == card));

                /* TK!! -- Have to check not only layoffs, but new layoffs opened up by a given layoff */
                /*foreach (var (card, meld) in permutation) {
                    meld.AsNear().PotentialCards();
                }*/

                if (remainingCardsAfterLayoffs.Count() <= 1) {
                    configurations.Add(new RummyConfiguration(meldConfiguration, layoffConfiguration, remainingCardsAfterLayoffs.SingleOrDefault()));
                    if (shortCircuit) return configurations;
                }
            }
        }

        return configurations;
    }
}